---
# tasks file for web_deploy

 - name: Update nginx
   yum: 
     name: nginx
     state: latest
   become: yes

 - name: Start and enable nginx
   systemd:
     name: nginx
     state: started
     enabled: yes
   become : true

 - name: Get current website tag
   stat:
     path: "/usr/share/nginx/{{ actual_tag }}/"
   register: is_equal_tag

# - name: var
#   debug:
#     var: is_equal_tag

 - block:
   - name: Creating dest dir with actual dir tag
     file: 
       dest: "/usr/share/nginx/{{ actual_tag }}/"
       state: directory
     become: yes

   - name: Move actual source code to dir
     copy:
       src: "web-source/"
       dest: "/usr/share/nginx/{{ actual_tag }}/"
     become: yes

   - name: Adding necessary chmod rules
     file:
       dest: "/usr/share/nginx/{{ actual_tag }}/"
       recurse: true
       mode: 0555
     become: true

   - name: Creating temp dir
     file:
       path: "/etc/nginx.tmp/"
       state: directory
     become: true

   - name: Importing jinja nginx configs to temp dir
     template: 
       src: "nginx/nginx.conf.j2"
       dest: "/etc/nginx.tmp/nginx.conf"
     become: yes

   - name: Importing nginx configs to temp dir
     copy:
       src: "nginx/"
       dest: "/etc/nginx.tmp/"
     become: true

   - name: Remove old nginx directory
     file:
       path: "/etc/nginx/"
       state: absent
     become: true

   - name: Rename temp dir
     command: "mv /etc/nginx.tmp/ /etc/nginx/"
     become: true
 
   - name: Reload nginx service
     systemd:
       name: nginx
       state: reloaded
     become: yes
   
   when: is_equal_tag.stat.exists == False

   rescue:
     - name: Clear imported website dir
       file:
         path: "/usr/share/nginx/{{ actual_tag }}/"
         state: absent
       become: true

     - name: Clear imported config dir
       file:
         path: "/etc/nginx.tmp"
         state: absent
       become: true
   
 - block:
   - name: Report error in tag naming
     debug:
       msg: "It looks like you did not update actual website tag. Please update it and try again"
  
   when: is_equal_tag.stat.exists == True
