---
# tasks file for lb_deploy

 - name: Updating haproxy
   yum: 
     name: haproxy
     state: latest

 - name: Start and enable haproxy
   systemd:
     name: haproxy
     enabled: true
     state: started

 - name: Creating temp dir for configs
   file:
     path: "/etc/haproxy.tmp/"
     state: directory
     mode: 0755
     owner: root
     group: root

 - name: Copying actual configs to temp dir
   template:
     src: "./haproxy.cfg.j2"
     dest: "/etc/haproxy.tmp/haproxy.cfg"
     owner: ec2-user
     group: ec2-user
     mode: 0600

 - name: Remove old config dir
   file:
     path: "/etc/haproxy/"
     state: absent

 - name: Rename temp to config dir
   command: "mv /etc/haproxy.tmp/ /etc/haproxy/"

 - name: Reload haproxy
   systemd:
     name: haproxy
     state: reloaded
