# Examples: use command "ansible-playbook -l <host> default_deployment.yaml" to specify target host

- name: Default deployment for new hosts
  hosts: all

  vars:
    home: "/home/ec2-user"
    
  tasks:
  - name: Installing epel-release
    yum:
      name: epel-release
      state: latest
    become: yes

  - name: Installing basic utilites
    yum:
      name: 
        - htop
        - vim
        - wget
        - git
        - bind-utils
      state: latest
    become: yes
  
  - name: Upload hostname file
    template:
      src: "{{ home }}/configfiles/templates/hostname.j2"
      dest: "{{ home }}/change-hostname"
      mode: 744

  - name: Changing hostname
    shell: 
      cmd: "{{ home }}/change-hostname"
    become: true

  - name: Deploy authorized keys file 
    copy:
      src:   "{{ home }}/.ssh/authorized_keys"
      dest:  "{{ home }}/.ssh/authorized_keys"
  
  - name: Deploy ssh-client configs
    copy: 
      src:   "/etc/ssh/ssh_config"
      dest:  "/etc/ssh/ssh_config"
    become: yes

  - name: Cleaning garbage
    file:
      path: "{{ home }}/change-hostname"
      state: absent
