# Examples: use command "ansible-playbook -l <host> default_deployment.yaml" to specify target host you want to configure

- name: Actual configs deployment
  gather_facts: false
  hosts: all
  vars:
    home: "/home/ec2-user"
    
  tasks:
  - name: Installing epel-release repo
    yum:
      name: epel-release
      state: latest
    become: yes

  - name: Installing basic utils
    yum:
      name: 
        - htop
        - vim
        - wget
        - git
        - bind-utils
        - java-1.8.0-openjdk
        - python2
        - python3
      state: latest
    become: yes

  - name: Getting target hostname
    ansible.builtin.command: hostname
    register: target_hostname

    #  - name: vars output
    #debug:
    #  var: target_hostname.stdout

  - block:
    - name: Upload target hostname file
      template:
        src: "{{ pwd }}/templates/hostname.j2"
        dest: "{{ home }}/change-hostname"
        mode: 744
  
    - name: Changing hostname
      shell: 
        cmd: "{{ home }}/change-hostname"
      become: true

    - name: Cleaning garbage
      file:
        path: "{{ home }}/change-hostname"
        state: absent 

    when: target_hostname.stdout != hostname

  - name: Deploy authorized_keys file 
    copy:
      src:   "{{ pwd }}/configs/ssh/authorized_keys"
      dest:  "{{ home }}/.ssh/authorized_keys"
 
  - name: Deploy ssh-client configs
    copy: 
      src:   "{{ pwd }}/configs/ssh/ssh_config"
      dest:  "/etc/ssh/ssh_config"
      owner: root
    become: yes

  - name: Import .bashrc file
    copy: 
      src:  "{{ pwd }}/configs/bash/bashrc"
      dest: "{{ home }}/.bashrc"
      owner: ec2-user
