---
 - name: Website deployment
   hosts: web
   become: yes

   tasks:
   - name: Installing nginx
     yum:
       name: nginx
       state: latest

   - name: Enable nginx service
     service: 
       name: nginx
       enabled: yes
       state: started

   - name: Copy actual website
     copy:
       src: /home/ec2-user/repo-from-github/web-source/
       dest: /usr/share/nginx/html/
...
