---
 - name: Deploy Actual DNS recors to dns server
   hosts: master
   gather_facts: false

   tasks:
     - name: Import DNS records to DNS server
       copy:
         src: "{{ pwd }}/configs/dns/"
         dest: "/var/named/"
       become: yes

     - name: Restart named service
       systemd:
         name: named
         state: restarted
       become: yes
