- name: Deploy nginx web server
  hosts: prod

  vars: 
    home: "/home/ec2-user"

  tasks:
  - name: Installing nginx
    yum: 
      name: nginx
      state: latest
    become: yes

  - name: Enable startup running for nginx service
    service:
      name: nginx
      enabled: yes
    become : true

  - name: Clear target directory
    file: 
      path: "/usr/share/nginx/html/"
      state: absent
    become: true

  - name: Copy source web page to target web server
    copy: 
      src: "/home/ec2-user/configfiles/web-source/"
      dest: "/usr/share/nginx/html/"
    become: true

  - name: Start nginx service
    service: 
      name: nginx
      state: started
    become: yes

