- name: Deploy nginx web server

  vars: 
    home: "/home/ec2-user"

  tasks:
  - name: Installing nginx
    yum: 
      name: nginx
      state: latest
    become: yes

  - name: Enable startup running for nginx service
    service:
      name: nginx
      enabled: yes
    become : true

  - name: Copy source web page to target web server
    file: 
      path: "/usr/share/nginx/html/"
      stet: absent
    copy: 
      src: "../web-source/*"
      dest: "/usr/share/nginx/html/"
