- name: Deploy nginx web server
  hosts: prod
  gather_facts: false

  vars: 
    home: "/home/ec2-user"

  tasks:
  - name: Installing nginx
    yum: 
      name: nginx
      state: latest
    become: yes

  - name: Importing nginx configs
    copy: 
      src: "./configs/nginx/"
      dest: /etc/nginx/
      force: yes
    become: yes

  - name: Enable startup running for nginx service
    service:
      name: nginx
      enabled: yes
    become : true

  - name: Clear target directory
    file: 
      path: "/usr/share/nginx/html/"
      state: absent
    become: true

  - name: Copy source web page to target web server
    copy: 
      src: "./web-source/"
      dest: "/usr/share/nginx/html/"
    become: true

  - name: Start nginx service
    service: 
      name: nginx
      state: started
    become: yes
  
